### ISSUE TITLE
Deep prop selectors

### ISSUE THREAD

**Issue by tvervest** [LUKKIEN/redux-needs#3]
In some situations it would be desirable to be able to give a property path, not just a property name, in the shape of `myprop.some.value`. In this situation the expected behaviour is that the need is only re-fired when the value of the property _path_ is changed (i.e. if `myprop` is changed, but `myprop.some.value` remains the same, the need should _not_ re-fire).

A situation where this is desirable is when using needs with React Native, where some parameters might be a sub-property of the `navigation.state.params` object, while the calculated navigation state is set to the component's `navigation` property by the React Navigation library.

I think simply [getting the values from the current property object](https://github.com/LUKKIEN/redux-needs/blob/develop/src/map-params.js#L2) using [_.get](https://lodash.com/docs/4.17.4#get) might be enough to add this feature.

**Comment by jjanssen** [comment]
Merged
